security:
  oauth2:
    client:
      #不多说了
      client-id: web
      client-secret: 654321
      #Token获取地址
      #access-token-uri: http://localhost:7001/auth-service/oauth/token
      #验证页面地址
      #user-authorization-uri: http://localhost:7001/auth-service/oauth/authorize
    resource:
      #Token信息获取和校验地址
      token-info-uri: http://localhost:7001/auth-service/oauth/check_token